EXEC sp_RENAME '[atp_players].[player]', 'id', 'COLUMN'
EXEC sp_RENAME '[atp_players].[Column 1]', 'first_name', 'COLUMN'
EXEC sp_RENAME '[atp_players].[Column 2]', 'last_name', 'COLUMN'
EXEC sp_RENAME '[atp_players].[Column 3]', 'dominant_hand', 'COLUMN'
EXEC sp_RENAME '[atp_players].[Column 4]', 'birth_date', 'COLUMN'
EXEC sp_RENAME '[atp_players].[Column 5]', 'country', 'COLUMN'
